# Generated by Django 5.0.9 on 2026-09-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador usado pelo conector (ex: 'inmet').", unique=True)),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('last_ingest_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="Código da estação na fonte original (ex: código INMET 'A652').", max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('station_type', models.CharField(choices=[('pluviometrica', 'Pluviométrica (chuva)'), ('hidrologica', 'Hidrológica (nível de rio)'), ('meteorologica', 'Meteorológica (completa)'), ('mare', 'Maré/Oceanográfica'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('desconhecido', 'Desconhecido')], default='desconhecido', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('mare_m', 'Maré (m)')], max_length=20)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(help_text='Sempre em UTC.')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.station')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reading_type', models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('mare_m', 'Maré (m)')], max_length=20)),
                ('comparison', models.CharField(choices=[('gte', 'Maior ou igual a'), ('lte', 'Menor ou igual a')], default='gte', max_length=3)),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('atencao', 'Atenção'), ('alerta', 'Alerta'), ('alerta_maximo', 'Alerta máximo')], default='atencao', max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(blank=True, help_text='Deixe em branco para aplicar a regra a todas as estações do tipo de leitura.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.station')),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.alertrule')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reading')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='core.station')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='core_statio_latitud_1da7c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_station_per_source'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['station', 'reading_type', '-timestamp'], name='core_readin_station_7dd177_idx'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('station', 'reading_type', 'timestamp'), name='unique_reading_per_station_type_time'),
        ),
    ]
