# Generated by Django 5.0.9 on 2026-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='reading_type',
            field=models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('vento_rajada_ms', 'Rajada de vento (m/s)'), ('vento_dir_graus', 'Direção do vento (graus)'), ('mare_m', 'Maré (m)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_type',
            field=models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('vento_rajada_ms', 'Rajada de vento (m/s)'), ('vento_dir_graus', 'Direção do vento (graus)'), ('mare_m', 'Maré (m)')], max_length=20),
        ),
    ]
