# Generated by Django 4.2.30 on 2026-09-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alertrule_reading_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hidrologico', 'Aviso Hidrológico'), ('geologico', 'Aviso Geológico'), ('meteorologico', 'Nível de Severidade Meteorológica'), ('incendio', 'Risco de Incêndio Florestal')], max_length=20)),
                ('redec', models.CharField(help_text="Regional de Defesa Civil (ex: 'SERRANA I').", max_length=40)),
                ('municipio', models.CharField(blank=True, help_text='Só preenchido pra tipos com granularidade municipal (hoje: só Geológico).', max_length=120)),
                ('risco', models.CharField(choices=[('muito_baixo', 'Muito baixo'), ('baixo', 'Baixo'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('muito_alto', 'Muito alto')], max_length=20)),
                ('numero_externo', models.CharField(blank=True, help_text='ID do boletim/aviso na fonte original.', max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, default='CEMADEN-RJ - SEDEC', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'redec', 'municipio'],
            },
        ),
        migrations.AddConstraint(
            model_name='riskalert',
            constraint=models.UniqueConstraint(fields=('tipo', 'redec', 'municipio'), name='unique_risk_alert_scope'),
        ),
    ]
