# Generated by Django 4.2.30 on 2026-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_riskalert_riskalert_unique_risk_alert_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('pluviometrica', 'Pluviométrica (chuva)'), ('hidrologica', 'Hidrológica (nível de rio)'), ('meteorologica', 'Meteorológica (completa)'), ('mare', 'Maré/Oceanográfica'), ('sirene', 'Sirene/Alarme'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
